OUTPUT_ARCH(arm)
ENTRY(_init)


SECTIONS
{
	.init.text :
	{ 
		*(.init)
	} 
	.init.data :
	{
		*(.init.data)
	} 
	
	.text :	{
		*(.text)
	} 
	

	.rodata ALIGN(4) : 
	{
		*(.rodata) 
	} 

	
	__init_data = .;
	.data ALIGN(4)  : 
	{
        __data_start = .;
		*(.data .data.*)
        __data_end = .;
	} 
	


    .bss  ALIGN(4) :
    {
	_sbss = .;
     *(.dynbss)
     *(.bss .bss.* .gnu.linkonce.b.*)
     *(COMMON)
      _ebss = .;
    }  

  
  
	
	__HEAP_START = .;

}

